;*******************************************************************************
; Auxiliary macros
;*******************************************************************************
SUBENTRY .MACRO
          pha
          tya
          pha
          txa
          pha
          .ENDM

SUBEXIT  .MACRO
          pla
          tax
          pla
          tay
          pla
          rts
          .ENDM

